### PR TITLE
Create informative issue template

### PR DESCRIPTION
**Pull request by OshekharO**

### CODE REVIEW

**Comment by OshekharO** [comment]
Create three labels for issue: provider, enhancement and bug. For proper information 😀.

**Review by Zenda-Cross — CHANGES_REQUESTED** [review]
can you remove ' request new providers ' part, I can't take more requests cause I have already received too many

**Review by OshekharO — COMMENTED** [review]
Removed provider section

**Review by Zenda-Cross — APPROVED** [review]

**Comment by Zenda-Cross** [comment]
Thank you very much

**Pull request merged**
